$(document).ready(function(){
  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass("hide");
        $("#t1").removeClass("makeVisible");
      });
    });
  });

  $("#t2").click(function(){
    $("#d2").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d2").click(function(){
      $("#t2").addClass("makeVisible");
      $("#d2").addClass("hide");
      $("#t2").click(function(){
        $(".termList").removeClass("hide");
        $("#t2").removeClass("makeVisible");
      });
    });
  });

  $("#t3").click(function(){
    $("#d3").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d3").click(function(){
      $("#t3").addClass("makeVisible");
      $("#d3").addClass("hide");
      $("#t3").click(function(){
        $(".termList").removeClass();
        $("#t3").removeClass();
      });
    });
  });

  $("#t4").click(function(){
    $("#d4").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d4").click(function(){
      $("#t4").addClass("makeVisible");
      $("#d4").addClass("hide");
      $("#t4").click(function(){
        $(".termList").removeClass();
        $("#t4").removeClass();
      });
    });
  });


  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });


  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });

  $("#t1").click(function(){
    $("#d1").addClass("makeVisible");
    $(".termList").addClass("hide");
    $("#d1").click(function(){
      $("#t1").addClass("makeVisible");
      $("#d1").addClass("hide");
      $("#t1").click(function(){
        $(".termList").removeClass();
        $("#t1").removeClass();
      });
    });
  });


});
